#!/usr/bin/env python3

import click
import os
import sqlite3

# main.38.com.natureguides.birdguide.obb (original)

PACKAGE = "com.natureguides.birdguide"
ANDROID_STUDIO_PROJECTS_PATH = os.environ['STUDIO_PROJECT_PATH']
APP_PATH = f'{ANDROID_STUDIO_PROJECTS_PATH}/collins'
PLATFORM_TOOLS_PATH = os.environ['PLATFORM_TOOLS_PATH']
ADB = f'{PLATFORM_TOOLS_PATH}/adb.exe'

NUM_SPECIES_IMAGES = 792
PROJECT_DIR = "~/Dropbox/natureguides"

ASSETS_SOURCE_DIR = f'{PROJECT_DIR}/assets'
ASSETS_TARGET_DIR = f'{PROJECT_DIR}/Android/app/src/main/assets'

OBB_VERSION = 119
OBB_FILENAME = f'main.{OBB_VERSION}.{PACKAGE}.obb'

OBB_SOURCE_DIR = f'{PROJECT_DIR}/assets/expansion'
OBB_CREATION_PATH = f'{OBB_SOURCE_DIR}/{OBB_FILENAME}'

OBB_DESTINATION_DIR = f'/storage/emulated/0/Android/obb/{PACKAGE}'

OBB_DESTINATION_PATH = f'{OBB_DESTINATION_DIR}/{OBB_FILENAME}'

ORIGINALS_PATH = f'/Users/johngorenfeld/Dropbox/natureguides/assets/HD/Europe'
ORIGINAL_SPECIES_IMAGES_PATH = f'{ORIGINALS_PATH}/SpeciesImages'

DB_VERSION = 506
APP_PATH = '/home/john/johng/StudioProjects/collins/'
DB_FILENAME = f'Strix_BIRDGUIDE_v{DB_VERSION}.db'

STRIX_DB_PATH = f'{APP_PATH}/app/src/main/assets/databases/{DB_FILENAME}'

# Helper utils

def getIfromRGB(rgb):
    red = rgb[0]
    green = rgb[1]
    blue = rgb[2]
    RGBint = (red<<16) + (green<<8) + blue
    return RGBint


@click.group()
def cli():
    """Utilities for Nature Guides"""
    pass

@cli.group()
def settings():
   """Show Birdbrain's current config"""
   click.echo('\n\n\nBirdbrain config\n\n')


@cli.command()
def install():
    """Install APK on device"""
    DEBUG_APK_PATH = f'/Users/johngorenfeld/Dropbox/natureguides/Android/app/build/outputs/apk/debug/app-debug.apk'


@cli.command()
def status():
    """Reports OBB situation, audits assets"""
    
    click.echo(f'\n\n\n\nBirdbrain status report')
    click.echo(f'-----------------------')

    click.echo('\nApp version:')
    cmd = f'grep "versionCode" {APP_PATH}/app/build.gradle'
    os.system(cmd)

    click.echo('\nSet up for expansion pack version:')
    cmd = f'grep -A 1 "obbVersion" {APP_PATH}/app/build.gradle'
    os.system(cmd)

    click.echo('\nOn phone right now:')
    cmd = f'{ADB} shell ls {OBB_DESTINATION_DIR}'
    os.system(cmd)

    click.echo('\n\n')


@cli.command()
@click.option("--original", default=False, help="Use original version")
def pack(original):
    """Install OBB expansion pack on Android device"""
    if (original == True):
            destination_dir = OBB_DESTINATION_DIR_ORIGINAL
            version = 37
            app_package = "com.natureguides.birdguide"

    else:
            destination_dir = OBB_DESTINATION_DIR    
            version = OBB_VERSION
            app_package = PACKAGE

    filename = f'main.{version}.{app_package}.obb'
    destination_path = f'{destination_dir}/{filename}'
    cmd = f'{ADB} mkdir {destination_dir}'
    os.system(cmd)
    cmd = f'{ADB} push {OBB_SOURCE_DIR}/{filename} {destination_path}'
    click.echo(cmd)
    os.system(cmd)

@cli.command()
def unpack():
    """Remove OBB expansion pack from Android device"""

@cli.command()
def optimise():
    """Optimise images."""
        
@cli.command()
def boot():
    """Run app after installing OBB expansion pack"""
    pass

@cli.command()
def audit():
    """Check for missing media assets"""

    family_images = os.listdir(f'{ASSETS_SOURCE_DIR}/images/family')

    species_path = f'{ASSETS_SOURCE_DIR}/expansion/images/species'
    species_images = os.listdir(species_path) 
    click.echo(species_path)

    plumage_images = os.listdir(f'{ASSETS_SOURCE_DIR}/expansion/images/plumages')
    map_images = os.listdir(f'{ASSETS_SOURCE_DIR}/expansion/images/maps')

    click.echo(f'Found {len(family_images)} family image files')    
    click.echo(f'Found {len(species_images)} species image files')
    click.echo(f'Found {len(plumage_images)} plumage image files')

    if len(species_images) != NUM_SPECIES_IMAGES:
        missing = NUM_SPECIES_IMAGES - len(species_images)
        click.echo(f'{missing} species images are missing.')

@cli.command()
def missing():
    """List missing plates and stage originals in special dir for conversion"""

    original_species_images = os.listdir(f'{ORIGINAL_SPECIES_IMAGES_PATH}')
    our_species_images = os.listdir(f'{OBB_SOURCE_DIR}/images/species')

    click.echo(f'Found {len(original_species_images)} family image files')    
    click.echo(f'Found {len(our_species_images)} species images staged to be put into expansion pack')

    i = 0

    need_conversion = []

    for original in original_species_images:
        name = original[:-3] + "jpg"
        if name not in our_species_images:
            i = i + 1
            need_conversion.append(original)
            click.echo(f'{i}. {name}')
            
    click.echo(len(need_conversion))


#     for unconverted in need_conversion:
#         name = unconverted
#         click.echo(name)
#         cmd = f'cp {ORIGINAL_SPECIES_IMAGES_PATH}/{name} {PROJECT_DIR}/assets/images/missing/'
#         os.system(cmd)

#     click.echo(f'Copied {len(unconverted)} into staging directory, ready for batch conversion')


@cli.command()
def forge():
    """Build new expansion pack from assets"""

    # zip -r0 zipfilename.zip files-to-zip

    cmd = f'cd {OBB_SOURCE_DIR} && zip -r0 {OBB_FILENAME} ./ -x "*.obb"'
    click.echo(cmd)
    os.system(cmd)

    click.echo('Resulting in this OBB:')
    size_cmd = f'ls -lh {OBB_CREATION_PATH}'


@cli.command()
def plumagenames():
    """Fit plumage filenames to Strix entries"""
    pass

@cli.command()
def species():
     """Prepare species images"""
     cmd = 'mogrify -verbose -format jpg -background white -alpha remove -flatten -alpha off -define jpeg:extent=400kb -path /Users/johngorenfeld/Dropbox/natureguides/assets/expansion/images/species *.png'
     os.system(cmd)


@cli.command()
@click.argument('id')
def ref(id):
     """Get a Strix object's reference from its ID"""
     if id is None:
        print("Must provide valid Strix entity ID.")
        return

     query_key = f'SELECT entity_reference FROM strix_entities where entity_id={id}'
     conn = sqlite3.connect(STRIX_DB_PATH)
     c = conn.cursor()

     for row in c.execute(query_key):
          ref = row[0]

     click.echo(ref)

@cli.command()
@click.argument('ref')
def id(ref):
     """Get a Strix object's ID from its reference"""
     if ref is None:
        print("Must provide valid Strix entity reference.")
        return

     query_key=f'SELECT entity_id FROM strix_entities WHERE entity_reference={ref}'
     conn = sqlite3.connect(STRIX_DB_PATH)
     c = conn.cursor()

     for row in c.execute(query_key):
          id = row[0]

     click.echo(id)

@cli.command()
@click.argument('category')
@click.argument('ref')
def name(category, ref):
     """Compose filename to follow NatureGuides nomenclature"""

     # Future version of this can support other categories but right
     # now this is strictly for songs.

     if category is not "song":
        print("Unsupported object category")
        return

     # Songs

     new_name = f'{ref}.m4a'
     click.echo(new_name)


@cli.command()
@click.argument('category')
@click.argument('name')
def modernname(self, category, name):
     """Determine modern name for Tengio file"""

     # Future version of this can support other categories but right
     # now this is strictly for songs.

     if category is not "song":
        print("Unsupported object category")
        return

     # Songs

     id = name.split('.')[0]
     ref = self.ref(id)
     song_name = f'{ref}.m4a'
     click.echo(song_name)


     
if __name__ == '__main__':
    cli()
